[package]
name = "theseus-kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
theseus-shared = { path = "../shared" }
log = { workspace = true }
acpi = { workspace = true }
uefi-raw = "0.1.0"
x86_64 = { workspace = true, optional = true, default-features = false, features = ["instructions","inline_asm"] }
spin = { workspace = true, optional = true }
volatile = { workspace = true, optional = true }
linked_list_allocator = { workspace = true, optional = true }
raw-cpuid = { workspace = true, optional = true }


# Release profile defined in workspace root

[features]
default = ["new_arch"]
new_arch = [
    "x86_64",
    "spin",
    "volatile",
    "linked_list_allocator",
    "raw-cpuid",
]
