[package]
name = "theseus-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
acpi = { workspace = true }
x86_64 = { workspace = true, default-features = false }
raw-cpuid = { workspace = true }

# features not needed
