[package]
name = "hobbyos-bootloader"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hobbyos_efi"
path = "src/main.rs"

[dependencies]
hobbyos-shared = { path = "../shared" }
uefi = { workspace = true }
log = { workspace = true }
acpi = { workspace = true }

# Release profile defined in workspace root
