[package]
name = "theseus-bootloader"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "theseus_efi"
path = "src/main.rs"

[dependencies]
theseus-shared = { path = "../shared" }
theseus-kernel = { path = "../kernel" }
uefi = { workspace = true }
log = { workspace = true }
acpi = { workspace = true }
x86_64 = { workspace = true, default-features = false, features = ["instructions"] }
spin = { workspace = true }
volatile = { workspace = true }
linked_list_allocator = { workspace = true }
raw-cpuid = { workspace = true }

[features]
kernel-tests = ["theseus-kernel/kernel-tests"]
kernel-test-scenario-fail = ["theseus-kernel/kernel-test-scenario-fail"]
kernel-test-scenario-panic = ["theseus-kernel/kernel-test-scenario-panic"]
kernel-test-scenario-hang = ["theseus-kernel/kernel-test-scenario-hang"]

# Release profile defined in workspace root
